HEMS_Test/Controllers/ProductTypeController.cs
using HEMS_Test.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using HEMS_Test.ViewModel;

namespace HEMS_Test.Controllers
{
    public class ProductTypeController : Controller
    {
        // GET: Product
        public ActionResult ProductTypes()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetProductTypes(DataTableAjaxPostModel model)
        {
            List<ProductType> data = new List<ProductType>();
            using (HEMS_Test.Models.HEMS_testEntities hEMS_TestEntities = new Models.HEMS_testEntities())
            {
                data = hEMS_TestEntities.ProductTypes.Include(x => x.ProductCategory)
                    .Where(x => x.Status == "ACTIVE").ToList();
            }
            var result = data.Select(x => new
            {
                x.Product_Type_Code,
                x.Type_Name,
                x.Type_Description,
                Create_Date = x.Create_Date.ToString("dd/MM/yyyy HH:mm"),
                Update_Date = x.Update_Date?.ToString("dd/MM/yyyy HH:mm"),
                x.ProductCategory.Category_Name,                
            });
            return Json(new
            {
                // this is what datatables wants sending back
                draw = model.draw,
                recordsTotal = data.Count,
                recordsFiltered = data.Count,
                data = result
            });
        }

        [HttpGet]
        public ActionResult CreateProductType()
        {
            return PartialView("Partials/CreateProductType", new ProductType());
        }

        [HttpPost]
        public ActionResult CreateProductType(ProductType model)
        {
            using (HEMS_testEntities entity = new HEMS_testEntities())
            {
                var ErrN = new System.Data.Entity.Core.Objects.ObjectParameter("ErrN", 0);
                var ErrM = new System.Data.Entity.Core.Objects.ObjectParameter("ErrM", "");

                entity.SaveProductType(new System.Data.Entity.Core.Objects.ObjectParameter("seq", 0),model.Product_Type_Code
                    , model.Product_Category_Code
                    , model.Type_Name
                    , model.Type_Description
                    , ErrN
                    , ErrM);

                return Json(new { result = (int)ErrN.Value, message = (string)ErrM.Value }, JsonRequestBehavior.AllowGet);
            }
        }

        
        [HttpGet]
        public ActionResult EditProductType(string code)
        {
            using (HEMS_testEntities entity = new HEMS_testEntities())
            {
                var model = entity.ProductTypes.FirstOrDefault((x => x.Status == "ACTIVE" && x.Product_Type_Code == code));
                return PartialView("Partials/EditProductType", model);
            }
        }

        [HttpGet]
        public JsonResult DeleteProductType(string code)
        {
            using (HEMS_testEntities entity = new HEMS_testEntities())
            {
                var errN = new System.Data.Entity.Core.Objects.ObjectParameter("ErrN", 0);
                var errM = new System.Data.Entity.Core.Objects.ObjectParameter("ErrM", "");
                var model = entity.DeleteProductType(code, errN, errM);
                return Json(new { result = (int)errN.Value, message = (string)errM.Value }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult EditProductType(ProductType model)
        {
            using (HEMS_testEntities entity = new HEMS_testEntities())
            {
                var ErrN = new System.Data.Entity.Core.Objects.ObjectParameter("ErrN", 0);
                var ErrM = new System.Data.Entity.Core.Objects.ObjectParameter("ErrM", "");

                entity.SaveProductType(new System.Data.Entity.Core.Objects.ObjectParameter("seq", 0), model.Product_Type_Code
                    , model.Product_Category_Code
                    , model.Type_Name
                    , model.Type_Description
                    , ErrN
                    , ErrM);

                return Json(new { result = (int)ErrN.Value, message = (string)ErrM.Value }, JsonRequestBehavior.AllowGet);
            }
        }
        

    }
}

HEMS_Test/Views/ProductType/Partials/CreateProductType.cshtml
@using HEMS_Test.Models

@model HEMS_Test.Models.ProductType

@{ 
    HEMS_testEntities entity = new HEMS_testEntities();
    List<ProductCategory> Categories = entity.ProductCategories.Where(x => x.Status == "ACTIVE").ToList();    
}
@using (Html.BeginForm("CreateProductType", "ProductType", FormMethod.Post, new { id = "form_CreateProductType" }))
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">
                New Product Type
            </div>
        </div>
        <div class="panel-body">
            <div class="col-md-12">
                <div class="col-md-12">
                    <div class="col-md-3">
                        <span class="bold">
                            Type Code
                        </span>
                    </div>
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Product_Type_Code, new { @class = "form-control", autocomplete = "off" })
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        <span class="bold">
                            Type Name
                        </span>
                    </div>
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Type_Name, new { @class = "form-control", autocomplete = "off" })
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        <span class="bold">
                            Type Description
                        </span>
                    </div>
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Type_Description, new { @class = "form-control", autocomplete = "off" })
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        <span class="bold">
                            Product Category
                        </span>
                    </div>
                    <div class="col-md-9">
                        @Html.DropDownListFor(m => m.Product_Category_Code, new SelectList(Categories.Select(x => new SelectListItem { Text = x.Category_Name, Value = x.Product_Category_Code }).ToList(), "Value", "Text"), new { @class = "form-control", onchange="changeCategory()", autocomplete = "off" })
                    </div>
                </div>                   
                <div class="col-md-12"></div>
            </div>
        </div>
    </div>
}

<script>
    
</script>

HEMS_Test/Views/ProductType/Partials/EditProductType.cshtml
@using HEMS_Test.Models

@model HEMS_Test.Models.ProductType

@using (Html.BeginForm("EditProductType", "ProductType", FormMethod.Post, new { id = "form_EditProductType" }))
{
    @Html.HiddenFor(x => x.Product_Type_Code)
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">
                Edit Product Type
            </div>
        </div>
        <div class="panel-body">
            <div class="col-md-12">
                <div class="col-md-12">
                    <div class="col-md-3">
                        <span class="bold">
                            Product Name
                        </span>
                    </div>
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Type_Name, new { @class = "form-control", autocomplete = "off" })
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        <span class="bold">
                            Product Description
                        </span>
                    </div>
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Type_Description, new { @class = "form-control", autocomplete = "off" })
                    </div>
                </div>
                <div class="col-md-12"></div>
            </div>
        </div>
    </div>
}

<script>
    
</script>