HEMS_Test/Models/ProductCategory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEMS_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
            this.ProductTypes = new HashSet<ProductType>();
        }
    
        public string Product_Category_Code { get; set; }
        public int Seq_Id { get; set; }
        public string Category_Name { get; set; }
        public string Category_Description { get; set; }
        public string Status { get; set; }
        public System.DateTime Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductType> ProductTypes { get; set; }
    }
}

HEMS_Test/Controllers/ProductCategoryController.cs
using HEMS_Test.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using HEMS_Test.ViewModel;

namespace HEMS_Test.Controllers
{
    public class ProductCategoryController : Controller
    {
        // GET: Product
        public ActionResult ProductCategories()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetProductCategories(DataTableAjaxPostModel model)
        {
            List<ProductCategory> data = new List<ProductCategory>();
            using (HEMS_Test.Models.HEMS_testEntities hEMS_TestEntities = new Models.HEMS_testEntities())
            {
                data = hEMS_TestEntities.ProductCategories
                    .Where(x => x.Status == "ACTIVE").ToList();
            }
            var result = data.Select(x => new
            {
                x.Product_Category_Code,
                x.Category_Name,
                x.Category_Description,
                Create_Date = x.Create_Date.ToString("dd/MM/yyyy HH:mm"),
                Update_Date = x.Update_Date?.ToString("dd/MM/yyyy HH:mm"),                
            });
            return Json(new
            {
                // this is what datatables wants sending back
                draw = model.draw,
                recordsTotal = data.Count,
                recordsFiltered = data.Count,
                data = result
            });
        }

        [HttpGet]
        public ActionResult CreateProductCategory()
        {
            return PartialView("Partials/CreateProductCategory", new ProductCategory());
        }

        [HttpPost]
        public ActionResult CreateProductCategory(ProductCategory model)
        {
            using (HEMS_testEntities entity = new HEMS_testEntities())
            {
                var ErrN = new System.Data.Entity.Core.Objects.ObjectParameter("ErrN", 0);
                var ErrM = new System.Data.Entity.Core.Objects.ObjectParameter("ErrM", "");

                entity.SaveProductCategory(new System.Data.Entity.Core.Objects.ObjectParameter("seq", 0),model.Product_Category_Code
                    , model.Category_Name
                    , model.Category_Description
                    , ErrN
                    , ErrM);

                return Json(new { result = (int)ErrN.Value, message = (string)ErrM.Value }, JsonRequestBehavior.AllowGet);
            }
        }

        
        [HttpGet]
        public ActionResult EditProductCategory(string code)
        {
            using (HEMS_testEntities entity = new HEMS_testEntities())
            {
                var model = entity.ProductCategories.FirstOrDefault((x => x.Status == "ACTIVE" && x.Product_Category_Code == code));
                return PartialView("Partials/EditProductCategory", model);
            }
        }

        [HttpGet]
        public JsonResult DeleteProductCategory(string code)
        {
            using (HEMS_testEntities entity = new HEMS_testEntities())
            {
                var errN = new System.Data.Entity.Core.Objects.ObjectParameter("ErrN", 0);
                var errM = new System.Data.Entity.Core.Objects.ObjectParameter("ErrM", "");
                var model = entity.DeleteProductCategory(code, errN, errM);
                return Json(new { result = (int)errN.Value, message = (string)errM.Value }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult EditProductCategory(ProductCategory model)
        {
            using (HEMS_testEntities entity = new HEMS_testEntities())
            {
                var ErrN = new System.Data.Entity.Core.Objects.ObjectParameter("ErrN", 0);
                var ErrM = new System.Data.Entity.Core.Objects.ObjectParameter("ErrM", "");

                entity.SaveProductCategory(new System.Data.Entity.Core.Objects.ObjectParameter("seq", 0)
                    , model.Product_Category_Code
                    , model.Category_Name
                    , model.Category_Description
                    , ErrN
                    , ErrM);

                return Json(new { result = (int)ErrN.Value, message = (string)ErrM.Value }, JsonRequestBehavior.AllowGet);
            }
        }
        

    }
}

HEMS_Test/Views/ProductCategory/Partials/CreateProductCategory.cshtml
@using HEMS_Test.Models

@model HEMS_Test.Models.ProductCategory


@using (Html.BeginForm("CreateProductCategory", "ProductCategory", FormMethod.Post, new { id = "form_CreateProductCategory" }))
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">
                New Product Category
            </div>
        </div>
        <div class="panel-body">
            <div class="col-md-12">
                <div class="col-md-12">
                    <div class="col-md-3">
                        <span class="bold">
                            Category Code
                        </span>
                    </div>
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Product_Category_Code, new { @class = "form-control", autocomplete = "off" })
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        <span class="bold">
                            Category Name
                        </span>
                    </div>
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Category_Name, new { @class = "form-control", autocomplete = "off" })
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        <span class="bold">
                            Category Description
                        </span>
                    </div>
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Category_Description, new { @class = "form-control", autocomplete = "off" })
                    </div>
                </div>                               
                <div class="col-md-12"></div>
            </div>
        </div>
    </div>
}

<script>
    
</script>

HEMS_Test/Views/ProductCategory/Partials/EditProductCategory.cshtml
@using HEMS_Test.Models

@model HEMS_Test.Models.ProductCategory

@using (Html.BeginForm("EditProductCategory", "ProductCategoryCategory", FormMethod.Post, new { id = "form_EditProductCategory" }))
{
    @Html.HiddenFor(x => x.Product_Category_Code)
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">
                Edit Product Category
            </div>
        </div>
        <div class="panel-body">
            <div class="col-md-12">
                <div class="col-md-12">
                    <div class="col-md-3">
                        <span class="bold">
                            Category Name
                        </span>
                    </div>
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Category_Name, new { @class = "form-control", autocomplete = "off" })
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        <span class="bold">
                            Category Description
                        </span>
                    </div>
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Category_Description, new { @class = "form-control", autocomplete = "off" })
                    </div>
                </div>
                <div class="col-md-12"></div>
            </div>
        </div>
    </div>
}

<script>
    
</script>